package com.springbootjsp.dto;

import java.util.Date;

public class FilesDto {  //一个文件传输对象
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.id
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.name
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.content
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.files
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private String files;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.remark
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.create_date
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.update_date
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.status
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private Integer status;


    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_files.is_delete
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    private Integer isDelete;

    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.id
     *
     * @return the value of v_files.id
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.id
     *
     * @param id the value for v_files.id
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.name
     *
     * @return the value of v_files.name
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.name
     *
     * @param name the value for v_files.name
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.content
     *
     * @return the value of v_files.content
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.content
     *
     * @param content the value for v_files.content
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.files
     *
     * @return the value of v_files.files
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.files
     *
     * @param files the value for v_files.files
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setFiles(String files) {
        this.files = files == null ? null : files.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.remark
     *
     * @return the value of v_files.remark
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.remark
     *
     * @param remark the value for v_files.remark
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.create_date
     *
     * @return the value of v_files.create_date
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.create_date
     *
     * @param createDate the value for v_files.create_date
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.update_date
     *
     * @return the value of v_files.update_date
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.update_date
     *
     * @param updateDate the value for v_files.update_date
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.status
     *
     * @return the value of v_files.status
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.status
     *
     * @param status the value for v_files.status
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_files.is_delete
     *
     * @return the value of v_files.is_delete
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_files.is_delete
     *
     * @param isDelete the value for v_files.is_delete
     *
     * @mbggenerated Tue May 12 15:19:28 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}